CREATE TABLE if not exists `users` (
	`Id` INT NOT NULL AUTO_INCREMENT,
	`Name` VARCHAR(50) NOT NULL,
	`Email` VARCHAR(35) NOT NULL,
	`Mobile` VARCHAR(20) NOT NULL DEFAULT '',
	`IsActive` BIT NOT NULL DEFAULT b'1',
	`IsDeleted` BIT NOT NULL DEFAULT b'0',
	`CreatedBy` INT NOT NULL DEFAULT '0',
	`CreatedDate` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`UpdatedBy` INT NOT NULL DEFAULT '0',
	`UpdatedDate` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	PRIMARY KEY (`Id`),
	UNIQUE INDEX `Name_Email` (`Name`, `Email`)
)
COLLATE='utf8mb4_general_ci';
